baseURL = 'https://kevzhang.top/'
languageCode = 'zh-cn'
# title = "kevzhang"
theme = "paper"

[params]
  enableReadingTime=true
  favicon = '/images/layers.ico'

  # color style
  color = 'linen'                 # linen, wheat, gray, light

  # header social icons
  github = 'kevcode1'       # github.com/YOUR_GITHUB_ID

  # home page profile
  avatar = 'GRAVATAR_EMAIL'       # Gravatar email or image url(e.g. "https://deno.land/logo.svg")
  name = 'kevzhang'
  bio = 'YOUR_BIO'

  # misc
  disableHLJS = true              # disable requesting highlight.js
  monoDarkIcon = false             # show monochrome dark mode icon