baseURL = 'https://kevzhang.top/'
languageCode = 'en-us'
DefaultContentLanguage = "zh"
title = "kevzhang's Blog"
theme = 'diary'

[params]
enableReadingTime=true
enableAutoDarkMode=true
favicon = '/images/layers.ico'

[[menu.main]]
url = "/about"
name = "关于"
weight = 3

[[menu.main]]
url = "/tags"
name = "标签"
weight = 2

[[menu.main]]
url = "/posts"
name = "归档"
weight = 1